# -*- coding: utf-8 -*-
"""ProgramaAlunos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYjx7uUy0AZl2sSbcCuBje9ZKfdbu_qf
"""

import json

lista_dd_alunos = []

while True:
  dd_aluno = {}

  dd_aluno["Nome"] = input("Digite o nome completo do aluno! (acentos não funcionam!)")
  dd_aluno["idade"] = input("Digite a idade do aluno!")
  Nota_1b = float(input("Digite a primeira nota do aluno!"))
  Nota_2b = float(input("Digite a segunda nota do aluno!"))
  Nota_3b = float(input("Digite a terceira nota do aluno!"))

  dd_aluno["Nota_1"] = Nota_1b
  dd_aluno["Nota_2"] = Nota_2b
  dd_aluno["Nota_3"] = Nota_3b

  nota_media = (Nota_1b + Nota_2b + Nota_3b) / 3

  if nota_media >= 7:
    dd_aluno["Resultado do ano"] = (f"Nota media: {nota_media} Aprovado")
  else:
    dd_aluno["Resultado do ano"] = (f"Nota media: {nota_media} Reprovado")

  lista_dd_alunos.append(dd_aluno)
  continuar = input("Você deseja cadastrar mais alunos? (Responda 's' para SIM, ou responda 'n' para NÃO)")
  if continuar.lower() != "s":
    break

with open("alunos.json", "w", encoding = "utf-8") as arquivo:
  json.dump(lista_dd_alunos, arquivo, indent=4)

olhar_lista = input("Deseja ver a lista de alunos? (Responda 's' para SIM, ou responda 'n' para NÃO)")

if olhar_lista.lower() == "s":
  print(json.dumps(lista_dd_alunos, indent=4))
else:
  print("Ok, lista salva no arquivo 'alunos.json'!")